### ISSUE TITLE
Sometimes getting User not Found error on server

### ISSUE THREAD

**Issue by RiddhiPan** [Sohagsrz/instagram-media-downloader#1]
Sometimes getting User not Found error on server but in local environment it works perfectly.. 

Please  give your suggestions for what to do to work it perfectly each time on Server

Thanks,

**Comment by Sohagsrz** [comment]
Some time its blocked the request, you can use proxy for it
`$downloader->withProxy();
$downloader->setProxy(
    'proxy.example.com',
    'username',
    'password'
);`

**Comment by RiddhiPan** [comment]
> Some time its blocked the request, you can use proxy for it `$downloader->withProxy(); $downloader->setProxy( 'proxy.example.com', 'username', 'password' );`

I have set proxy using below ->
$downloader = new Downloader();
        $downloader->withProxy();
        $downloader->setProxy(
            '{{server_url}}',
            '{{insta_username}}',
            '{{insta_password}}'
        );
            
        $downloader->set_user_agent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');
        $downloader->set_user_agent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15');
       
        $profileDownloader = new ProfileDownloader();    
        $allPost = $profileDownloader->getProfile({{insta_username}});    
        
Also i have tried it using ProfileDownloader class as follows ->

$profileDownloader = new ProfileDownloader();    
        $profileDownloader->withProxy();
        $profileDownloader->setProxy(
           '{{server_url}}',
            '{{insta_username}}',
            '{{insta_password}}'
        );
            
        $profileDownloader->set_user_agent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');
        $profileDownloader->set_user_agent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15');

 $allPost = $profileDownloader->getProfile({{insta_username}});    

     **Still it not works**
